Fix sidebar navigation links and errors in md files
threefoldtech/digital_me pull request #69
Opened 2018-11-27 11:50 UTC by ranatrk

#### What this PR resolves:
-Navigating to other wiki links don't work because the current namespace is appended to the previous when working with the different wiki repos:
eg: /wiki/foundation/grid instead of /wiki/grid
-Docs added from docsites include example folders that dont have _sidebar.md or readme.md files resulting in errors

#### Changes proposed in this PR:

- The whole url is changed to navigate from one wiki to the other instead of appending to the current url 
-Add temporary _sidebar.md and readme.md files

**Fixes**: #26

2018-11-28 09:46 UTC, rkhamis requested changes

2018-11-28 09:46 UTC, rkhamis commented on packages/dm_base/blueprints/wiki/routes.py
> +from flask import abort, redirect, url_for, send_from_directory
please remove unused import

2018-11-28 09:46 UTC, rkhamis commented on packages/dm_base/blueprints/wiki/routes.py
> +
please clean whitespace. I suggest you use a linter to show you these errors, will make your life a lot easier

2018-12-03 16:25 UTC, ranatrk commented on packages/dm_base/blueprints/wiki/routes.py
> +from flask import abort, redirect, url_for, send_from_directory
I updated the commit.

2018-12-03 16:26 UTC, ranatrk commented on packages/dm_base/blueprints/wiki/routes.py
> +
I updated it for now but will check out a linter for the future. Thank you.

2018-12-03 16:42 UTC, rkhamis approved these changes

2018-12-03 16:42 UTC, merged